name: mensa_links
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.1 #Used for state management
  get_storage: ^2.0.3 #Used to store data locally
#  USED FOR ANIMATION
  animated_check: ^1.0.5 #Used to show animated check mark
  liquid_progress_indicator: ^0.4.0
  simple_animations: ^4.0.2

  flutter_svg: ^1.0.3 #Used to show svg images
  pin_code_fields: ^7.4.0 #Used to crete pin fields
  qr_code_scanner: ^0.7.0 #Used to scan QR Code (Temporarliy used for Design)
  mask_text_input_formatter: ^2.3.0 #Use for formatting Inputs
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  blinkid_flutter: ^5.15.1
  flutter_mrz_scanner:
    path: ./flutter_mrz_scanner
  mrz_parser: ^2.0.0
  permission_handler: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
   - family: Ubuntu
     fonts:
       - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
         weight: 300
       - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
         weight: 400
       - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
         weight: 500
       - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
         weight: 700